<?php
/**
 * Created by PhpStorm.
 * User: stacy
 * Date: 2019/04/26
 * Time: 09:32
 */

use Sop\CryptoEncoding\PEM;
use Sop\CryptoTypes\AlgorithmIdentifier\Hash\SHA256AlgorithmIdentifier;
use Sop\CryptoTypes\AlgorithmIdentifier\Signature\SignatureAlgorithmIdentifierFactory;
use Sop\CryptoTypes\Asymmetric\PrivateKeyInfo;
use X501\ASN1\Name;
use X509\CertificationRequest\CertificationRequestInfo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

require dirname(__DIR__) . "/vendor/autoload.php";
//
//// load EC private key from PEM
//$private_key_info = PrivateKeyInfo::fromPEM(
//    PEM::fromString("-----BEGIN PRIVATE KEY-----
//MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkHkHVAGooJSTm/GB
//TgeLi6LyTGdkEtXLuRAtmnQIyyChRANCAARsOoVm4oaaFOHVIFIgwAKpnlxGdbgJ
//CI9KskIfcYU9GyfdKY0skjmlL66sTJB8EPiiy+N/DUm/8FBA4tUiyPi1
//-----END PRIVATE KEY-----"));
//// extract public key from private key
//$public_key_info = $private_key_info->publicKeyInfo();
//// DN of the subject
//$subject = Name::fromString("cn=example.com, O=Example\, Inc., C=US");
//// create certification request info
//$cri = new CertificationRequestInfo($subject, $public_key_info);
//// sign certificate request with private key
//$algo = SignatureAlgorithmIdentifierFactory::algoForAsymmetricCrypto(
//    $private_key_info->algorithmIdentifier(), new SHA256AlgorithmIdentifier());
//$csr = $cri->sign($algo, $private_key_info);
//echo $csr;
//
//
//$cert = "-----BEGIN CERTIFICATE-----
//MIIELzCCAhcCAhAnMA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNVBAYTAlpBMRAwDgYD
//VQQIDAdHYXV0ZW5nMRswGQYDVQQKDBJpU29sdiBUZWNobm9sb2dpZXMxFjAUBgNV
//BAMMDWlzb2x2dGVjaC5jb20xITAfBgkqhkiG9w0BCQEWEmluZm9AaXNvbHZ0ZWNo
//LmNvbTAeFw0xOTA2MDUxMzE3MzhaFw0yMDA2MTQxMzE3MzhaMEMxCzAJBgNVBAYT
//AlVTMRUwEwYDVQQKDAxFeGFtcGxlIEluYy4xHTAbBgNVBAMMFGNlcnRpZmljYXRl
//MDUwNjIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAur4iR/Mc
//48E5yoPrUWSYlniWMn9tdKac3hNYQ/hQPywtrnPN0r8Pe18rxPbWcEz5phPZ14n7
//gMkhUuVBGAqO9OmMYo0Wud93+sZ2+rhzaaF1287ukv70F0xw9Zm6uF/GXfpEz9DX
//tmQkgqyIOWTQ1wnHXk9ReAlGIvJMuTn1iZ4MCpcQ2tpgDdzfa5iVoCEqkIBzB/dk
//nunDBfKOBGWgZmuTuEdKeYGj1HS2tsWbOOEu9EO/BJxyN9p5CyVo98df7GVhvomN
//f2TBQL4bBSdiSA0VgRnEZoPmgrYvzeYMWaNAU0U6Fkw/MCV1jo/fyAYfc0u5dmQP
//mFaMB04NbRWnXQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBDS4mHkIxzn/vljSOr
//zgXWlvcfKpDLfiFTuqToOYR8XCgBXv3Vw9lMZvDUHjtvFQv5d3q6Y8YZ9nhgQGYX
//0qEo1L0YqUM3yMJLunb7Kr2PdH2/3gVeUETOlR5aqhjKNUO5HWG9Rs3Adt9eIXIH
//omJbIulpbXii1sr5rUlh8K+C7WqE+tvNC2Iq9qy1ixXiDbo7tG7ebmKT51CTlFVk
//POuwqEE6ojfYCfd8w6oz9YkmixfqacRJah6mccbSot2FGcz++vH+ADC+1UjsGSlX
//DvfxIiS9wUd9VcEt1Yg6vJwo+N+sH2ikjzGoPid1vFJm/tyBHcxiEC6D30vEfBZr
//wzr4CpmrsDNN51DPLL6R8K5E5wbIamTMlnMZHISRfIzZCI7lqNHOfn0lX767YVZs
//Z7/GkyKCV7UzNQgfT3bwZBzIInb40HxSC7Odli26pHdSQ9qhNHLFXwNeGj18L9rU
//UUelVsnS3UHuIK68Oz+xvWqQCvKlOlGfhnCBtunT+DbguDrmEfB/IRX+8/qtDzMN
//vFs/RKzioBbDfrtmNQjWMClVdiyp7ZCzD6/H9vT1BXeKwNmU1OS6RqiJZ4CBSiVI
//tFkmcF3j9pQ5BithAmd8wgm9wTzw1dAgklqUvUcqiuex1yDeMLn4zewCZ2+XZRU7
//hCqu2vx4bFslBiEBoDGbDnucJg==
//-----END CERTIFICATE-----";
//print(json_encode($cert));
//$resource = openssl_pkey_get_public($cert);
//    var_dump( $resource);

//$my_file = new File("C:\\Users\\Stacy\\Desktop\\Document signer\\Doc1.docx");
function generateUniqueFileName()
{
    // md5() reduces the similarity of the file names generated by
    // uniqid(), which is based on timestamps
    return md5(uniqid());
}
$my_file = new UploadedFile("C:\\Users\\Stacy\\Desktop\\Document signer\\Doc1.docx","Doc1.docx");

var_dump($my_file);
$fileName = generateUniqueFileName().'.'.$my_file->guessExtension();


//$pdf_base64 = "C:\\Users\\Stacy\\Desktop\\Document signer\\Doc1.docx";


//Get File content from txt file
//$pdf_base64_handler = fopen($pdf_base64,'r');
//$pdf_content = fread ($pdf_base64_handler, filesize($pdf_base64));
//fclose ($pdf_base64_handler);
////Decode pdf content
//$pdf_decoded = base64_decode ($pdf_content);
////Write data back to pdf file
//$pdf = fopen ('C:\\Users\\Stacy\\Desktop\\Document signer\\test.docx','w');
//fwrite ($pdf,$pdf_decoded);
////close output file
//fclose ($pdf);
//echo 'Done';